
# Minimal Test Config
hh:
  N: 20  # Tiny network
  density: 0.2
task:
  narma_order: 5 
  poisson_rate_min: 10
  poisson_rate_max: 50
  symbol_ms: 20
  dt: 0.1
  lyap_window: [10, 50]

rho_grid_coarse: [0.1]
bias_grid_coarse: [0.0]
seeds_coarse: 1
sweep_mode: coarse
results_dir: "/home/atkaw/Dokumenty/hailitacja/eservoir_hh/project_C_poisson/results_test"
cache_dir: "/home/atkaw/Dokumenty/hailitacja/eservoir_hh/project_C_poisson/cache_test"
